import '../categories/house types/offices/odata.dart';
import '../categories/house types/residential/rdata.dart';

class Property {
  String label;
  String name;
  String price;
  String location;
  String sqm;
  String review;
  String description;
  String frontImage;
  String ownerImage;
  String ownerName;
  List<String> images;

  Property(
      this.label,
      this.name,
      this.price,
      this.location,
      this.sqm,
      this.review,
      this.description,
      this.frontImage,
      this.ownerImage,
      this.ownerName,
      this.images);
}

List<Property> getPropertyList() {
  return <Property>[
    Property(
      "SALE",
      "Clinton Villa",
      "3,500.500",
      "Los Angeles",
      "2,456",
      "4.4",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/house_01.jpg",
      "assets/images/user3.jpg",
      "Malicka Sanchez",
      [
        "assets/images/kitchen.jpg",
        "assets/images/bath_room.jpg",
        "assets/images/swimming_pool.jpg",
        "assets/images/bed_room.jpg",
        "assets/images/living_room.jpg",
      ],
    ),
    Property(
      "SALE",
      "North Light",
      "1,500.500",
      "Anchorage",
      "1,456",
      "4.4",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/oHouse1.jpg",
      "assets/images/user1.jpg",
      "Larrissa Lowrens",
      [
        "assets/images/kitchen.jpg",
        "assets/images/bath_room.jpg",
        "assets/images/swimming_pool.jpg",
        "assets/images/bed_room.jpg",
        "assets/images/living_room.jpg",
      ],
    ),
    Property(
      "RENT",
      "JCDecaux WorkSpaces",
      "150.000",
      "Boston",
      "650",
      "4.5",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/JCDecaux.jpg",
      "assets/images/logo_size.png",
      "DomArt",
      [
        "assets/images/theCrown.jpg",
        "assets/images/appleCampus.jpg",
        "assets/images/philipsTower.jpg",
        "assets/images/bureau.jpg",
        "ssets/images/empirestateBulding.jpg",
      ],
    ),
    Property(
      "RENT",
      "The Yellow Foot Building",
      "3,500.000",
      "San Diego",
      "3,100",
      "4.5",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/yellow-foot-residential-building-oa-lab_6.jpg",
      "assets/images/logo_size.png",
      "DomArt",
      [
        "assets/images/immeuble.jpg",
        "assets/images/nbc-g365201f2a_1920.jpg",
        "assets/images/mall-g2ad4c8504_1920.jpg",
        "assets/images/city-g6dc609ce4_1920.jpg",
        "assets/images/architecture-gfe4e13806_1920.jpg",
      ],
    ),
    Property(
      "SALE",
      "Ibe House",
      "4,500.000",
      "Florida",
      "4,100",
      "4.5",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/house_03.jpg",
      "assets/images/user11.jpg",
      "James Saint esprit",
      [
        "assets/images/kitchen.jpg",
        "assets/images/bath_room.jpg",
        "assets/images/swimming_pool.jpg",
        "assets/images/bed_room.jpg",
        "assets/images/living_room.jpg",
      ],
    ),
    Property(
      "SALE",
      "Aventura",
      "5,200.000",
      "New York",
      "3,100",
      "4.2",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/house_05.jpg",
      "assets/images/user10.jpg",
      "Deckard Shaw",
      [
        "assets/images/kitchen.jpg",
        "assets/images/bath_room.jpg",
        "assets/images/swimming_pool.jpg",
        "assets/images/bed_room.jpg",
        "assets/images/living_room.jpg",
      ],
    ),
    Property(
      "RENT",
      "NBC Queens HQ",
      "4,500.000",
      "Queens",
      "5,100",
      "4.5",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/nbc-g365201f2a_1920.jpg",
      "assets/images/logo_size.png",
      "DomArt",
      [
        "assets/images/immeuble.jpg",
        "assets/images/mall-g2ad4c8504_1920.jpg",
        "assets/images/architecture-gfe4e13806_1920.jpg",
        "assets/images/city-g6dc609ce4_1920.jpg",
        "assets/images/yellow-foot-residential-building-oa-lab_6.jpg",
      ],
    ),
    Property(
      "SALE",
      "North House",
      "3,500.000",
      "Florida",
      "3,700",
      "4.0",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/house_06.jpg",
      "assets/images/owner.jpg",
      "Priscilla Molovish",
      [
        "assets/images/kitchen.jpg",
        "assets/images/bath_room.jpg",
        "assets/images/swimming_pool.jpg",
        "assets/images/bed_room.jpg",
        "assets/images/living_room.jpg",
      ],
    ),
    Property(
      "RENT",
      "Rasmus Resident",
      "2,900",
      "Detroit",
      "2,700",
      "4.3",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/house_07.jpg",
      "assets/images/user1.jpg",
      "Lorenzo terrada",
      [
        "assets/images/kitchen.jpg",
        "assets/images/bath_room.jpg",
        "assets/images/swimming_pool.jpg",
        "assets/images/bed_room.jpg",
        "assets/images/living_room.jpg",
      ],
    ),
    Property(
      "RENT",
      "Simone House",
      "3,900",
      "Florida",
      "3,700",
      "4.4",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/house_08.jpg",
      "assets/images/user2.jpg",
      "Dominique torreto",
      [
        "assets/images/kitchen.jpg",
        "assets/images/bath_room.jpg",
        "assets/images/swimming_pool.jpg",
        "assets/images/bed_room.jpg",
        "assets/images/living_room.jpg",
      ],
    ),
    Property(
      "RENT",
      "The Mandalorian",
      "75.000",
      "Atlanta",
      "2,150",
      "4.4",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/theMandalorian.jpg",
      "assets/images/logo_size.png",
      "DomArt",
      [
        "assets/images/bureau.jpg",
        "assets/images/JCDecaux.jpg",
        "assets/images/philipsTower.jpg",
        "assets/images/theCrown.jpg",
        "assets/images/appleCampus.jpg",
      ],
    ),
    Property(
      "RENT",
      "Apple Campus",
      "100.000",
      "Cuepertino",
      "2,000",
      "4.6",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/appleCampus.jpg",
      "assets/images/logo_size.png",
      "DomArt",
      [
        "assets/images/theMandalorian.jpg",
        "assets/images/bureau.jpg",
        "assets/images/theCrown.jpg",
        "assets/images/JCDecaux.jpg",
        "assets/images/empirestateBulding.jpg",
      ],
    ),
    Property(
      "RENT",
      "Empire state Building",
      "80.000",
      "New York",
      "800",
      "4.1",
      "The living is easy in this impressive, generously proportioned contemporary residence with lake and ocean views, located within a level stroll to the sand and surf.",
      "assets/images/empirestateBulding.jpg",
      "assets/images/logo_size.png",
      "DomArt",
      [
        "assets/images/philipsTower.jpg",
        "assets/images/theCrown.jpg",
        "assets/images/bureau.jpg",
        "assets/images/JCDecaux.jpg",
        "assets/images/appleCampus.jpg",
      ],
    ),
  ];
}
