// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX1CjurcTWe09IkubbHGetP14UQ4hfybQ',
    appId: '1:416701562134:web:ff2f88ba5eb212bfce2437',
    messagingSenderId: '416701562134',
    projectId: 'domart-68b7f',
    authDomain: 'domart-68b7f.firebaseapp.com',
    storageBucket: 'domart-68b7f.appspot.com',
    measurementId: 'G-GQTE825LEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjCDlpZP_EAN6cQbAIAe5bwpeRrPI1ciQ',
    appId: '1:416701562134:android:a272cb364209e1c8ce2437',
    messagingSenderId: '416701562134',
    projectId: 'domart-68b7f',
    storageBucket: 'domart-68b7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOvzBSZxft40nkDr5OKFQPGhoSwe0qt4',
    appId: '1:416701562134:ios:9a6b079cc928b230ce2437',
    messagingSenderId: '416701562134',
    projectId: 'domart-68b7f',
    storageBucket: 'domart-68b7f.appspot.com',
    iosClientId: '416701562134-3umram6iohf26379k1tc1atvk46dakc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMOvzBSZxft40nkDr5OKFQPGhoSwe0qt4',
    appId: '1:416701562134:ios:9a6b079cc928b230ce2437',
    messagingSenderId: '416701562134',
    projectId: 'domart-68b7f',
    storageBucket: 'domart-68b7f.appspot.com',
    iosClientId: '416701562134-3umram6iohf26379k1tc1atvk46dakc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstate',
  );
}
